name: Deploy MkDocs site

permissions:
  contents: read
  id-token: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Build site
        run: mkdocs build

      - name: Add CNAME for custom domain
        run: echo 'docs.citra.space/keplemon' > site/CNAME

      - uses: actions/configure-pages@v3

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: site

      - uses: actions/deploy-pages@v1
