name: test

on:
  push:
    branches:
      - main

jobs:
  test-linux-arm:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build for ${{ matrix.python-version }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/io \
            -e HOME=/root \
            -w /io quay.io/pypa/manylinux2014_aarch64 \
            bash -c '
              yum install -y curl gcc gcc-c++ make openssl-devel openssl && \
              export CARGO_HOME="$HOME/.cargo" && export RUSTUP_HOME="$HOME/.rustup" && \
              curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable && \
              source "$CARGO_HOME/env" && \
              cargo install --locked cargo-make && \
              cargo install --locked maturin && \
              export OPENSSL_DIR=/usr && \
              export OPENSSL_LIB_DIR=/usr/lib64 && \
              export OPENSSL_INCLUDE_DIR=/usr/include && \
              cargo make copy-linux-arm && \
              PYTHON_VERSION=${{ matrix.python-version }} && \
              TAG=${PYTHON_VERSION//./} && \
              PY_BIN=/opt/python/cp${TAG}-cp${TAG}/bin/python && \
              PIP="${PY_BIN%/python}/pip" && \
              $PIP install --upgrade pip setuptools wheel auditwheel && \
              maturin build --release --compatibility manylinux2014 -i $PY_BIN
            '
