name: test

on:
  push:
    branches:
      - test

jobs:
  test-windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          cargo install --locked cargo-make
          pip install ".[dev]"

      - name: Test build
        run: cargo make test-windows

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: windows-whl
          path: target/wheels/*.whl

  test-linux-amd:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          cargo install --locked cargo-make
          pip install ".[dev]"

      - name: Test build
        run: cargo make test-linux-amd

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: linux-amd-whl
          path: target/wheels/*.whl

  test-macos-arm:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          cargo install --locked cargo-make
          pip install ".[dev]"

      - name: Test build
        run: cargo make test-mac-arm

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: mac-arm-whl
          path: target/wheels/*.whl

  test-macos-amd:
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          cargo install --locked cargo-make
          pip install ".[dev]"

      - name: Test build
        run: cargo make test-mac-amd

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: mac-amd-whl
          path: target/wheels/*.whl
